apiVersion: v1
kind: Service
metadata:
  name: clinic-management-system-service
  namespace: clinic-management-system
  labels:
    app: clinic-management-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: clinic-management-system